
services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
      MYSQL_USER: team_joshua
      MYSQL_PASSWORD: lac_ojt_applus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - app_network

  # Laravel Backend Service
  backend:
    build: ./backend
    container_name: laravel_container
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    environment:
      DB_HOST: mysql
      DB_DATABASE: backend
      DB_USERNAME: team_joshua
      DB_PASSWORD: lac_ojt_applus
    command: php artisan serve --host=0.0.0.0

  # Next.js Frontend Service
  frontend:
    build: ./frontend
    container_name: nextjs_container
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    command: npm run dev
    environment:
      - NODE_ENV=development 
      #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
      - WATCHPACK_POLLING=true
    

networks:
  app_network:

volumes:
  mysql_data: