<?php
namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        Employee::insert([
            [
                'first_name' => 'John',
                'middle_name' => 'A.',
                'last_name' => 'Doe',
                'suffix' => '',
                'gender' => 'male',
                'birthdate' => '1990-01-01',
                'civil_status' => 'single',
                'nationality' => 'Filipino',
                'region' => 'NCR',
                'province' => 'Metro Manila',
                'city_or_municipality' => 'Quezon City',
                'barangay' => 'Bagumbayan',
                'street' => '123 Main St',
                'phone_number' => '09171234567',
                'emergency_contact1' => 'Jane Doe',
                'emergency_contact2' => 'Jake Doe',
                'email' => 'john.doe@example.com',
                'job_position_id' => 1,
                'date_hired' => '2022-01-15',
                'employment_type_id' => 1,
                'manager_id' => null,
                'profile_pic_url' => 'applus-image1.png',
                'tin_number' => '123-456-789',
                'sss_number' => '01-2345678-9',
                'pagibig_number' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'bank_number' => '1234567890',
            ],
            [
                'first_name' => 'Maria',
                'middle_name' => 'B.',
                'last_name' => 'Santos',
                'suffix' => '',
                'gender' => 'female',
                'birthdate' => '1985-05-10',
                'civil_status' => 'married',
                'nationality' => 'Filipino',
                'region' => 'IV-A',
                'province' => 'Laguna',
                'city_or_municipality' => 'Calamba',
                'barangay' => 'Real',
                'street' => '456 South St',
                'phone_number' => '09181234567',
                'emergency_contact1' => 'Pedro Santos',
                'emergency_contact2' => 'Juan Santos',
                'email' => 'maria.santos@example.com',
                'job_position_id' => 2,
                'date_hired' => '2021-06-01',
                'employment_type_id' => 2,
                'manager_id' => 1,
                'profile_pic_url' => 'applus-image2.png',
                'tin_number' => '987-654-321',
                'sss_number' => '98-7654321-0',
                'pagibig_number' => '4321-8765-2109',
                'philhealth_number' => '98-765432109-8',
                'bank_number' => '0987654321',
            ],
            [
                'first_name' => 'Carlos',
                'middle_name' => 'C.',
                'last_name' => 'Reyes',
                'suffix' => '',
                'gender' => 'male',
                'birthdate' => '1992-09-20',
                'civil_status' => 'single',
                'nationality' => 'Filipino',
                'region' => 'VII',
                'province' => 'Cebu',
                'city_or_municipality' => 'Cebu City',
                'barangay' => 'Lahug',
                'street' => '789 North St',
                'phone_number' => '09191234567',
                'emergency_contact1' => 'Ana Reyes',
                'emergency_contact2' => 'Luis Reyes',
                'email' => 'carlos.reyes@example.com',
                'job_position_id' => 3,
                'date_hired' => '2023-03-10',
                'employment_type_id' => 1,
                'manager_id' => 2,
                'profile_pic_url' => 'applus-image3.png',
                'tin_number' => '321-654-987',
                'sss_number' => '32-1654987-1',
                'pagibig_number' => '5678-1234-0987',
                'philhealth_number' => '32-165498701-3',
                'bank_number' => '1122334455',
            ],
        ]);
    }
}
